export const mockProjects = [
  {
    slug: 'mateflow',
    title: 'MateFlow',
    subtitle: 'Fitness coaching funnel',
    category: 'Web Apps',
    image: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    overview: 'A complete fitness coaching platform with personalized onboarding, progress tracking, and subscription management.',
    challenge: 'Create a seamless user experience that converts visitors into paying subscribers while maintaining high performance and accessibility.',
    solution: 'Built a progressive web app with Next.js 14, implementing server-side rendering for SEO, optimistic UI updates, and a custom animation system for engagement.',
    stack: ['Next.js 14', 'TypeScript', 'Prisma', 'PostgreSQL', 'Stripe', 'TailwindCSS'],
    metrics: [
      { label: 'Conversion Rate', value: '+127%' },
      { label: 'Page Load Time', value: '0.8s' },
      { label: 'User Retention', value: '92%' },
    ],
  },
  {
    slug: 'clinica-norte',
    title: 'Clínica Norte',
    subtitle: 'Appointments & lead gen',
    category: 'Landing',
    image: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    overview: 'Medical clinic website with online appointment booking, doctor profiles, and lead generation system.',
    challenge: 'Design a trustworthy, accessible platform that simplifies appointment scheduling for both patients and staff.',
    solution: 'Developed a headless CMS-powered site with real-time availability checking, automated email confirmations, and multi-language support.',
    stack: ['Next.js', 'Sanity CMS', 'React Query', 'Nodemailer', 'Framer Motion'],
    metrics: [
      { label: 'Online Bookings', value: '+312%' },
      { label: 'Admin Time Saved', value: '15h/week' },
      { label: 'Patient Satisfaction', value: '4.8/5' },
    ],
  },
  {
    slug: 'estancia',
    title: 'Estancia',
    subtitle: 'Real estate showcase',
    category: 'Landing',
    image: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    overview: 'Luxury real estate showcase with virtual tours, interactive maps, and lead capture forms.',
    challenge: 'Create an immersive experience that showcases properties while maintaining fast load times and mobile responsiveness.',
    solution: 'Built a Next.js application with optimized image delivery, lazy-loaded 3D tours, and a custom parallax scrolling system.',
    stack: ['Next.js', 'Three.js', 'Mapbox', 'CloudinaryOptimized images', 'GSAP'],
    metrics: [
      { label: 'Time on Site', value: '+4.2min' },
      { label: 'Qualified Leads', value: '+89%' },
      { label: 'Mobile Traffic', value: '68%' },
    ],
  },
  {
    slug: 'pampa-saas',
    title: 'Pampa SaaS',
    subtitle: 'Waitlist & onboarding',
    category: 'Web Apps',
    image: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)',
    overview: 'SaaS product waitlist with email automation, early access program, and seamless onboarding flow.',
    challenge: 'Build hype and capture qualified leads before product launch while providing early adopters with a premium experience.',
    solution: 'Created a conversion-optimized landing page with dynamic waitlist positioning, referral system, and progressive onboarding.',
    stack: ['Next.js', 'Resend', 'Upstash Redis', 'Clerk Auth', 'Recharts'],
    metrics: [
      { label: 'Waitlist Signups', value: '12.4K' },
      { label: 'Referral Rate', value: '43%' },
      { label: 'Early Access CVR', value: '67%' },
    ],
  },
]
